# Example Site settings

#google_analytics: UA-NNNNNNNN-N

title: 'mathilda nguyen'
description: 'Maths + CS undergrad researcher'
header_pages:
  - index.md
  - about.md
  - availability.md

footer: ''

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag

theme: jekyll-theme-minimal
