# Example Site settings

#google_analytics: UA-NNNNNNNN-N

title: 'mathilda nguyen'
description: ''
header_pages:
  - index.md
  - maths.md
  - about.md
  - availability.md

footer: ''

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
  - jekyll-latex
  - jekyll-spaceship

theme: jekyll-theme-minimal

defaults:
  values:
    mathjax: true
markdown: kramdown
kramdown:
  math_engine: mathjax
